# Generated by Django 5.0.3 on 2024-03-06 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PessoBancoDeDados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primeiro_nome', models.CharField(max_length=20, verbose_name='Meu primeiro nome')),
                ('segundo_nome', models.CharField(max_length=20, verbose_name='Meu segundo nome')),
                ('idade', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Minha idade')),
            ],
        ),
    ]
